name: Workflow-CI Push Github & Docker

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/data/python-learning-performance_preprocessing.csv'

jobs:
  mlflow-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          
      - name: Check Env
        run: |
          echo $CSV_URL
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run MLflow project
        run: |
          mlflow run MLproject

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/*/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Copy MLflow Artifacts
        run: |
          mkdir -p model_artifacts
          EXP_ID=$(ls mlruns | head -n 1)
          cp -r mlruns/$EXP_ID/${{ env.RUN_ID }}/artifacts/model model_artifacts/

      - name: Upload Artifact to GitHub Repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
          git add model_artifacts/
          git commit -m "chore: upload mlflow artifacts for run ${{ env.RUN_ID }}" || echo "No changes to commit"
          git push origin main

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            -m "runs:/${{ env.RUN_ID }}/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/student-performance-prediction:latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/student-performance-prediction:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student-performance-prediction:latest
